### PR TITLE
Fix issue #7 (usage of stdint.h types)

### PR DESCRIPTION
**Pull request by antoinealb**

### CODE REVIEW

**Comment by antoinealb** [comment]
Just rebased against `cvra/master`.

**Comment by antoinealb** [comment]
Well, when we decided on how we should handle integers, I will rebase against `cvra/master` before merging.

**Comment by antoinealb** [comment]
Pull request rebased against `master`. Anyone care to merge ?

**Comment by pierluca** [comment]
LGTM

**Pull request merged**
