### PR TITLE
uCOS-III semaphore implementation

### PR DESCRIPTION
**Pull request by msplr**
Same as in PR #35:
- changed the API to static allocation
- breaks the mock implementation and it's tests
- didn't test it on hardware yet

### CODE REVIEW

**Comment by antoinealb** [comment]
Same reactions as #35 : Timeout should be microseconds and I can take a look at the mock issue if you want.

**Comment by msplr** [comment]
ok for me

**Comment by antoinealb** [comment]
LGTM

**Comment by msplr** [comment]
Merge?

**Pull request merged**
