### PR TITLE
Fix issue #11 (non-blocking pend / with timeout)

### PR DESCRIPTION
**Pull request by froj**
I chose `float` milliseconds for the timeout as it seems to be the most readable.

### CODE REVIEW

**Comment by antoinealb** [comment]
Code looks good to me. Maybe the design decisions to handle negative timeout value as just a try feels a bit weird but ok.

Maybe add a line or two to the README about non-blocking functions ?

**Comment by froj** [comment]
> Maybe the design decisions to handle negative timeout value as just a try feels a bit weird but ok.

It's either that or hard fail, I guess.

**Comment by pierluca** [comment]
Does negative time-out ever make sense? If not, fail hard (in mock)

PS: where can I find the uC/OS-III documentation? I'd need to read some of
it to be more relevant with my remarks.

**Comment by froj** [comment]
> Does negative time-out ever make sense? If not, fail hard (in mock)

OK, we'll let it fail hard.

@pierluca [uC/OS-III doc](https://doc.micrium.com/display/osiiidoc/uC-OS-III+Documentation+Home)

**Comment by Stapelzeiger** [comment]
I'm against using float milliseconds for the timeout. If we use float, then it should consistently be in SI units so we never need to convert units.
I would prefer to use an uint32_t in microseconds since this is much less overhead on systems without an FPU.

**Comment by pierluca** [comment]
uint32_t in microseconds seems reasonable.
That means an overflow after about 72 minutes.
We're not going that far, are we ? ;-)

**Comment by antoinealb** [comment]
What is the overflow of uc/OS-III ?

**Comment by froj** [comment]
> What is the overflow of uc/OS-III ?

It's `uint32` OS-ticks.

**Comment by antoinealb** [comment]
Ok, so we can safely allow `uint32_t` microseconds.

**Pull request merged**
